### ISSUE TITLE
Pineberry Pi | Hatdrive! | PCIe timeout: 0X001e08f | Failed to open device: 'nvme' | Cannot boot from nvme drive

### ISSUE THREAD

**Issue by GAndrianopoulos** [PineberryPi/pineberry-docs.github.io#9]
On boot I receive the following message 
Boot mode:NVME (06) order F41
PCIe timeout: 0X001e08f
Failed to open device: 'nvme'

I ordered 3 HATdrives and 3 Raspberry pi 5 around the same time, I received the drives a little bit later a few day's after Christmas.
 
All hardware are new for a specific project. 
Hardware:
  3X Raspberry pi 5 8GB (New)
  3X Raspberry pi 27W charger (New)
  3X WDC PC SN530 256GB SSD (Used)
  3X SanDisk HCI A1 10 16GB (New)
  3X HATDrive! Top (Order number 2800)

The I followed the instructions down below. 
https://docs.pineberrypi.com/tutorial-booting-from-nvme
https://docs.pineberrypi.com/tutorial-connecting-your-hatdrive

Steps to replicate are the following (Please note I have the exact same issue on all 3 instances)
1. Clean install of Raspbian full X64 with Pi Imager on SD card
2. Clean install of Raspbian light X64 with Pi Imager on NVME drive
3. boot raspbian from SD to logon screen
4. Perform a sudo apt-get update and sudo apt-get upgrade
5. redo step 4, no updates and upgrades are available.
6. Reboot
7. Change the BOOT_ORDER line to BOOT_ORDER=0xf416 added PCIE_PROBE=1 
8. Saved the file and reboot
9. Checked it file was saved.
10.  Shutdown 
11.  Removed power and SD card
12. installed HATDrive
13. Inserted power adapter
14. During boot error appears. Boot mode:NVME (06) order F41 PCIe timeout: 0X001e08f Failed to open device: 'nvme'

I also tried to add dtparam=nvme and dtparam=pciex1_gen=3 on the /boot/config.txt without any luck.

When i do a lsblk command I do see the nvme drive with its 2 partitions.
Before you ask, yes I'm able to read and write files from and to the nvme drive.
With dmesg --follow no errors are registered.

Please help as I don't now what to do next.

Attachments
Photo of boot error:
![WhatsApp Image 2024-01-05 at 14 53 44 (1)](https://github.com/PineberryPi/pineberry-docs.github.io/assets/79792223/92ce3e12-434c-4e16-b7ff-48d72f14c322)

Photo of  device list using lsblk
![WhatsApp Image 2024-01-05 at 14 53 43](https://github.com/PineberryPi/pineberry-docs.github.io/assets/79792223/9af519a2-d942-4337-bea5-93dfc4799b6f)

Photo of nvme info using lspci -vvvv
![WhatsApp Image 2024-01-05 at 14 53 44](https://github.com/PineberryPi/pineberry-docs.github.io/assets/79792223/45c379ab-49f5-423e-9c41-a01c7116712b)

**Comment by mlewus** [comment]
Many WD drives are known to be incompatible with both the pi 4 compute module, and the pi 5. Please refer to Pineberry’s drive compatibility list here [https://github.com/PineberryPi/pineberry-docs.github.io/blob/main/nvme-compatibility-list.md](url)

**Comment by GAndrianopoulos** [comment]
@mlewus, Thank you for pointing this out, however the SSD drive which I am using is stated and on the top of the  NVMe compatibility list.

**Comment by Arthur-Philip-Dent** [comment]
Two questions from my side: 
1) did you connect the HATDrive! Top with the ribbon cable only, or did you use the "GPIO Header extension socket"? 
2) if you used the extension socket, which version did you use? 40-pin or 28-pin? 

I had a problem with the 28-pin extension, that the disk got incredibly hot and was not availabe. 
Just as an idea if you used the GPIO header extender: leave out the header extender and only using FPC ribbon cable? 

The Hitchhiker!


<img src="https://github.com/PineberryPi/pineberry-docs.github.io/assets/108473979/29348a2c-cf28-41e0-8f4b-6181d30dfe75" alt="Raspi 5 with HATDrive! Top, screw up spacer for ssd and no GPIO header extender" width="25%" height="25%">

**Comment by GAndrianopoulos** [comment]
@Arthur-Philip-Dent 

Found it! 

As I removed the 40-pin header extension from the Pi's board and only used the FPC cable it now works.
So before while the board was only connected to the FPC cable, the 40-pin header was on the pi's board but disconnected from the HatDrive. When also removing the header from the pi's board it magically works which blows my mind as the 40-pin extension header should only extend the pins.

I will add the link of the 40-pins extension header which apparently is causing booting issues at my end 
https://www.kiwi-electronics.com/nl/40-pin-gpio-stapel-header-2x20-female-extra-hoog-3986

**Comment by Arthur-Philip-Dent** [comment]
GrEaT! <3

I had an extender, which was delivered with the HATDRive! Top, so I guess, its something, we both might have missed in configuring - or it is really an issue on the hardware.
One one the guys of Pineberry should have a look into it and comment it here.

**Comment by mfolejewski** [comment]
@Arthur-Philip-Dent
I'm not sure if I would agree with you regarding HAT connector, and if this part might cause such an issue.
In the past, we noticed a strange behavior when using such a particular Samsung NVMe drive in cooperation with the CM4 module (abnormal heating).

What can I say from a hardware designer's point of view? Raspberry Pi 5 (and CM4 as well) has numerous compatibility issues with PCIe-attached devices. In most cases, it's firmware/bootloader-related issues with detecting and booting OS.

We noticed many incompatible NVMe SSD drives, such as e.g. WD Black/Blue/Green series (they use Sandisk controller).

Generally speaking, it's the NVMe lottery.

I hope that sooner or later they fix issues about PCIe compatibility because we received a noticeable quantity of feedback from our users regarding NVMe drives and Raspberry Pi 5.

Some NVMe drives have OS boot issues under PCIe Gen3 and work fine with Gen2 only -> e.g. Lexar NM620 (it might be an issue related to not certified Gen3 mode - the PCIe timings are close to the tech spec limits).

**Comment by Arthur-Philip-Dent** [comment]
Thanks for sorting out things and going into details! 
During time of build of my system, I didn’t come across problema with the Samsung PM9B1, 512GB Gen4x4. And sorry, that I removed the sticker before attaching a heatsink. This was stupid from me, since you could see the SSD model in the picture. 

That said, I’m glad this thingy is running like hell and you are still “in business” building great hardware. 
Awaiting, what’s coming next! (Ok, SSDs, got it, waiting for a 2242…).

**Comment by mlewus** [comment]
FWIW I have had great results with the Acer Predator GM 3500 (gen 3) and GM 7000 (gen4) drives. I have one each in my two pi 5s, both booting from Pineberry bottom hats.
